language: rust

rust:
  # NOTE: Change back to stable after 2018 Edition merged.
  # - stable
  # - beta
  - nightly

os:
  # - osx
  - linux

cache:
  timeout: 360
  cargo: true

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

env:
  global:
    - RUST_BACKTRACE: full
    - CRATE_NAME: rust_algorithm_club
    - BOOK_DIR: .book

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh

script:
  - sh ci/script.sh

after_script:
  - set +e

before_deploy:
  - sh ci/before-deploy.sh

deploy:
  provider: pages
  target-branch: gh-pages
  local-dir: "$BOOK_DIR"
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    # NOTE: Change back to stable after 2018 Edition merged.
    condition: "$TRAVIS_RUST_VERSION = nightly"

branches:
  only:
    # release tags
    - /^v?\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
