[book]
title = "Rust Algorithm Club"
authors = ["Weihang Lo"]
description = "Learn algorithms and data structures with Rust"

[build]
build-dir = ".book"
create-missing = false

[output.html]
curly-quotes = true
mathjax-support = true
no-section-label = true
google-analytics = "UA-118441906-1"
